### ISSUE TITLE
App needs an icon

### ISSUE THREAD

**Issue by MrTanoshii** [MrTanoshii/rusty-autoclicker#1]
The app needs an icon; a mouse clicking may be nice?

**Comment by Aditeya** [comment]
Hi, I really liked your project and decided to create an icon for it. Hope you like it and please do let me know if I should do any changes.

icon preview:
![image](https://user-images.githubusercontent.com/22963960/188303403-e14804bc-ec0d-42ef-b7f4-624f49bb8c6c.png)

icon png:
![rusty-autoclicker](https://user-images.githubusercontent.com/22963960/188303384-7f045ab4-bb97-4960-9502-fc31cce01c30.png)

icon svg:
![rusty-autoclicker](https://user-images.githubusercontent.com/22963960/188303439-9e692dcd-52f9-41e9-921c-e1801277a7aa.svg)

**Comment by MrTanoshii** [comment]
Thank you very much, I love it

It will be implemented soon!
