### ISSUE TITLE
Remove hardcoded app icon in favor of soft linked using path

### ISSUE THREAD

**Issue by MrTanoshii** [MrTanoshii/rusty-autoclicker#14]
## Problem

The app icon is currently hardcoded in [icon.rs](https://github.com/MrTanoshii/rusty-autoclicker/blob/main/src/icon.rs). This gets the job done but is not ideal.

I have previously tried using [include_bytes](https://doc.rust-lang.org/std/macro.include_bytes.html) but did not have any luck.

## Solution

The app icon should be provided to the code as a link and embedded in the binary during `cargo build

The path should be the relative link to the icon in the assets folder: `./assets/icon-64x64.ico`

**Comment by ChancellorCeti** [comment]
I would like to work on this, could you assign it to me?
