### ISSUE TITLE
Unable to start application on MacOS

### ISSUE THREAD

**Issue by cph-w** [MrTanoshii/rusty-autoclicker#17]
Mac OS Monterrey 12.6 with no external mouse connected

```
thread 'main' panicked at 'index out of bounds: the len is 5 but the index is 5', src/app.rs:747:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This issue is caused by the device_query::MouseState returning less button_pressed than is accessed by index for the UI button pressed string. This causes a panic and the application is not usable.

**Comment by MrTanoshii** [comment]
Fixed in #18 

Thank you
