### ISSUE TITLE
Should autoclick counter be reset after completion?

### ISSUE THREAD

**Issue by frankschmitt** [MrTanoshii/rusty-autoclicker#21]
While working on #12 , I noticed that the autoclick counter isn't being reset after the configured number of clicks has been performed:

```
// Increment click counter and stop autoclicking if completed
self.click_counter += 1u64;
if click_amount != 0u64 && self.click_counter >= click_amount {
  self.is_autoclicking = false;
}

```
Therefore, when you re-enter autoclick mode, the app only performs a single click  (unless you set it to 0 = infinite clicking). Is this intentional?

**Comment by MrTanoshii** [comment]
https://github.com/MrTanoshii/rusty-autoclicker/blob/8267a3569e86928951b346436a4bf956edf1762c/src/app.rs#L196-L204

It's reset in `start_autoclick()`.
I tested it and it works as intended on my the main branch on my side, can you provide detailed steps so I can try and reproduce it please?

**Comment by frankschmitt** [comment]
@MrTanoshii Hm. I can't reproduce it either - neither in my branch nor in the main branch. I guess I had messed it up during development, sorry for the noise.
