### ISSUE TITLE
App does not run on Windows

### ISSUE THREAD

**Issue by MrTanoshii** [MrTanoshii/rusty-autoclicker#31]
### Working
- `cargo run (--release)`
- `.\target\release\rusty-autoclicker.exe`

### Not Working
- `cargo build (--release)`
- Double click `.exe` to launch

It seems to be starting as I can see the icon appearing briefly on my taskbar and in task manager.

**Comment by nozwock** [comment]
> It seems to be starting as I can see the icon appearing briefly on my taskbar and in task manager.

This is the exact bug I was going to talk about 😂, will talk about the solution tommorow. I'm out to sleep

TL:DR it's due to that app icon or whatever it's called function in `main.rs`, It tries to look for `assets\your_icon_file` in the pwd of the app and panics if it fails to find it.

**Comment by MrTanoshii** [comment]
Haha, I just found it too
#15 introduced it. I have a lot to learn about being a maintainer still
